name: ğŸ— Lint & Build

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      â€“ uses: actions/checkout@v3
      â€“ uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      â€“ run: npm ci

      - name: Lint code
      â€“ run: npm run lint